deleted:
  - atlas_attacks
  - atlas_attacks_2d
  - atlas_attacks_30d
  - atlas_attacks_7d
  - atlas_botnets
  - atlas_botnets_2d
  - atlas_botnets_30d
  - atlas_botnets_7d
  - atlas_fastflux
  - atlas_fastflux_2d
  - atlas_fastflux_30d
  - atlas_fastflux_7d
  - atlas_phishing
  - atlas_phishing_2d
  - atlas_phishing_30d
  - atlas_phishing_7d
  - atlas_scans
  - atlas_scans_2d
  - atlas_scans_30d
  - atlas_scans_7d
  - bitcoin_blockchain_info
  - bitcoin_nodes
  - blocklist_de_ircbot
  - bm_tor
  - chaosreigns_iprep0
  - chaosreigns_iprep100
  - chaosreigns_iprep50
  - cleantalk_top20
  - cta_cryptowall
  - darklist_de
  - dragon_http
  - dragon_sshpauth
  - dragon_vncprobe
  - gofferje_sip
  - infiltrated
  - jigsaw_attacks
  - jigsaw_malware
  - multiproxy
  - openbl
  - openbl_180d
  - openbl_1d
  - openbl_30d
  - openbl_360d
  - openbl_60d
  - openbl_7d
  - openbl_90d
  - openbl_all
  - palevo
  - proxyrss
  - proxyspy
  - ri_connect_proxies
  - ri_web_proxies
  - sorbs_anonymizers
  - sorbs_block
  - sorbs_escalations
  - sorbs_new_spam
  - sorbs_noserver
  - sorbs_recent_spam
  - sorbs_smtp
  - sorbs_web
  - sorbs_zombie
  - sp_anti_infringement
  - sp_atma
  - sp_spammers
  - trustedsec_atif
  - virbl
