renames:
  compromised: et_compromised
  critical_context_aws_cloud: provider_context_aws_cloud
  critical_context_digitalocean_geofeed: provider_context_digitalocean_geofeed
  critical_context_gcp_cloud: provider_context_gcp_cloud
  critical_context_linode_geofeed: provider_context_linode_geofeed
  critical_context_oracle_cloud: provider_context_oracle_cloud
  critical_context_vultr_geofeed: provider_context_vultr_geofeed
  danmetor: dm_tor
  emerging_block: et_block
  ib_abuse_palevo: iblocklist_abuse_palevo
  ib_abuse_spyeye: iblocklist_abuse_spyeye
  ib_bluetack_ads: iblocklist_ads
  ib_bluetack_bogons: iblocklist_bogons
  ib_bluetack_dshield: iblocklist_dshield
  ib_bluetack_edu: iblocklist_edu
  ib_bluetack_exclusions: iblocklist_exclusions
  ib_bluetack_fornonlancomputers: iblocklist_fornonlancomputers
  ib_bluetack_forumspam: iblocklist_forumspam
  ib_bluetack_hijacked: iblocklist_hijacked
  ib_bluetack_iana_multicast: iblocklist_iana_multicast
  ib_bluetack_iana_private: iblocklist_iana_private
  ib_bluetack_iana_reserved: iblocklist_iana_reserved
  ib_bluetack_level1: iblocklist_level1
  ib_bluetack_level2: iblocklist_level2
  ib_bluetack_level3: iblocklist_level3
  ib_bluetack_ms: iblocklist_org_microsoft
  ib_bluetack_proxies: iblocklist_proxies
  ib_bluetack_rangetest: iblocklist_rangetest
  ib_bluetack_spider: iblocklist_spider
  ib_bluetack_spyware: iblocklist_spyware
  ib_bluetack_webexploit: iblocklist_webexploit
  ib_ciarmy_malicious: iblocklist_ciarmy_malicious
  ib_cidr_report_bogons: iblocklist_cidr_report_bogons
  ib_cruzit_web_attacks: iblocklist_cruzit_web_attacks
  ib_isp_aol: iblocklist_isp_aol
  ib_isp_att: iblocklist_isp_att
  ib_isp_cablevision: iblocklist_isp_cablevision
  ib_isp_charter: iblocklist_isp_charter
  ib_isp_comcast: iblocklist_isp_comcast
  ib_isp_embarq: iblocklist_isp_embarq
  ib_isp_qwest: iblocklist_isp_qwest
  ib_isp_sprint: iblocklist_isp_sprint
  ib_isp_suddenlink: iblocklist_isp_suddenlink
  ib_isp_twc: iblocklist_isp_twc
  ib_isp_verizon: iblocklist_isp_verizon
  ib_malc0de: iblocklist_malc0de
  ib_onion_router: iblocklist_onion_router
  ib_org_activision: iblocklist_org_activision
  ib_org_apple: iblocklist_org_apple
  ib_org_blizzard: iblocklist_org_blizzard
  ib_org_crowd_control: iblocklist_org_crowd_control
  ib_org_electronic_arts: iblocklist_org_electronic_arts
  ib_org_joost: iblocklist_org_joost
  ib_org_linden_lab: iblocklist_org_linden_lab
  ib_org_logmein: iblocklist_org_logmein
  ib_org_ncsoft: iblocklist_org_ncsoft
  ib_org_nintendo: iblocklist_org_nintendo
  ib_org_pandora: iblocklist_org_pandora
  ib_org_pirate_bay: iblocklist_org_pirate_bay
  ib_org_punkbuster: iblocklist_org_punkbuster
  ib_org_riot_games: iblocklist_org_riot_games
  ib_org_sony_online: iblocklist_org_sony_online
  ib_org_square_enix: iblocklist_org_square_enix
  ib_org_steam: iblocklist_org_steam
  ib_org_ubisoft: iblocklist_org_ubisoft
  ib_org_xfire: iblocklist_org_xfire
  ib_pedophiles: iblocklist_pedophiles
  ib_spamhaus_drop: iblocklist_spamhaus_drop
  ib_yoyo_adservers: iblocklist_yoyo_adservers
  maxmind_geolite2: maxmind_geolite2_asn
  stop_forum_spam: stopforumspam
  stop_forum_spam_1h: stopforumspam_1d
  stop_forum_spam_7d: stopforumspam_7d
  stop_forum_spam_30d: stopforumspam_30d
  stop_forum_spam_90d: stopforumspam_90d
  stop_forum_spam_180d: stopforumspam_180d
  stop_forum_spam_365d: stopforumspam_365d
  tor: et_tor
