package engine

import (
	"fmt"
	"strings"
	"time"

	"github.com/firehol/update-ipsets/pkg/cache"
	"github.com/firehol/update-ipsets/pkg/config"
	"github.com/firehol/update-ipsets/pkg/iprange"
	"github.com/firehol/update-ipsets/pkg/output"
)

func (e *Engine) syncGeneratedFiles(generated []output.GeneratedFile, webPublished []string) error {
	if err := output.SyncGit(output.SyncOptions{
		BaseDir:       e.runtime.BaseDir,
		PushToGit:     e.runtime.PushToGit,
		PushMerged:    e.runtime.PushToGitMerged,
		CommitOptions: strings.Fields(e.runtime.PushToGitCommitOptions),
		PushOptions:   strings.Fields(e.runtime.PushToGitPushOptions),
	}, generated); err != nil {
		return err
	}
	outDir := e.outputDir()
	if e.runtime.PushToGitWeb && outDir != e.runtime.BaseDir {
		if len(webPublished) > 0 {
			webGenerated := make([]output.GeneratedFile, 0, len(webPublished))
			for _, path := range webPublished {
				webGenerated = append(webGenerated, output.GeneratedFile{Path: path, Redistributable: true})
			}
			return output.SyncGit(output.SyncOptions{
				BaseDir:       outDir,
				PushToGit:     true,
				PushMerged:    e.runtime.PushToGitMerged,
				CommitOptions: strings.Fields(e.runtime.PushToGitCommitOptions),
				PushOptions:   strings.Fields(e.runtime.PushToGitPushOptions),
			}, webGenerated)
		}
		return output.SyncGit(output.SyncOptions{
			BaseDir:       outDir,
			PushToGit:     true,
			PushMerged:    e.runtime.PushToGitMerged,
			CommitOptions: strings.Fields(e.runtime.PushToGitCommitOptions),
			PushOptions:   strings.Fields(e.runtime.PushToGitPushOptions),
		}, filterGeneratedFiles(outDir, generated))
	}
	return nil
}

func (e *Engine) renderHeader(name string, src *config.Source, hash string, finalSet *iprange.IPSet, sourceMTime time.Time) []byte {
	var buf strings.Builder
	quantity := fmt.Sprintf("%d unique IPs", finalSet.UniqueCount())
	if hash == "net" {
		quantity = fmt.Sprintf("%d subnets, %d unique IPs", finalSet.Entries(), finalSet.UniqueCount())
	}
	// Aggregation for the header: 0 for base ipsets, specific window
	// for history variants (e.g. 1440 for _1d). This matches the bash
	// which passes hmins=0 for the base finalize call.
	aggregation := aggregationMinutesFromName(name)
	fmt.Fprintf(&buf, "#\n# %s\n#\n", name)
	fmt.Fprintf(&buf, "# %s hash:%s ipset\n#\n", src.IPV, hash)
	for _, line := range wrapInfo(src.Info) {
		fmt.Fprintf(&buf, "# %s\n", line)
	}
	fmt.Fprintf(&buf, "#\n# Maintainer      : %s\n", src.Maintainer)
	fmt.Fprintf(&buf, "# Maintainer URL  : %s\n", src.MaintainerURL)
	fmt.Fprintf(&buf, "# List source URL : %s\n", publicURL(src))
	fmt.Fprintf(&buf, "# Source File Date: %s\n#\n", posixDate(sourceMTime.UTC()))
	fmt.Fprintf(&buf, "# Category        : %s\n", src.Category)
	fmt.Fprintf(&buf, "# Version         : %d\n#\n", e.state.Entry(name).Snapshot().Version+1)
	fmt.Fprintf(&buf, "# This File Date  : %s\n", posixDate(e.now().UTC()))
	fmt.Fprintf(&buf, "# Update Frequency: %s\n", minutesText(src.Frequency))
	fmt.Fprintf(&buf, "# Aggregation     : %s\n", minutesText(aggregation))
	fmt.Fprintf(&buf, "# Entries         : %s\n#\n", quantity)
	fmt.Fprintf(&buf, "# Full list analysis, including geolocation map, history,\n")
	fmt.Fprintf(&buf, "# retention policy, overlaps with other lists, etc.\n")
	fmt.Fprintf(&buf, "# available at:\n#\n#  %s%s\n#\n", e.runtime.WebURL, name)
	fmt.Fprintf(&buf, "# Generated by FireHOL's update-ipsets\n#\n")
	return []byte(buf.String())
}

func (e *Engine) renderSetInfo(name string, entry *cache.Entry) string {
	quantity := fmt.Sprintf("%d unique IPs", entry.UniqueIPs)
	if entry.Hash == "net" {
		quantity = fmt.Sprintf("%d subnets, %d unique IPs", entry.Entries, entry.UniqueIPs)
	}
	// Bash conditionally includes "from [this link]" only for redistributable sets.
	redistributable := e.isRedistributable(name)
	freq := minutesText(entry.FrequencyMinutes)
	if redistributable && entry.PublicURL != "" {
		return fmt.Sprintf("[%s](%s%s)|%s|%s hash:%s|%s|updated every %s from [this link](%s)\n",
			name, e.runtime.WebURL, name, entry.Info, entry.IPV, entry.Hash, quantity, freq, entry.PublicURL)
	}
	return fmt.Sprintf("[%s](%s%s)|%s|%s hash:%s|%s|updated every %s\n",
		name, e.runtime.WebURL, name, entry.Info, entry.IPV, entry.Hash, quantity, freq)
}

// posixDate formats a time in the POSIX locale format used by
// "date -u" in the bash script: "Mon Mar 30 07:44:35 UTC 2026".
// This matches the C locale default: "%a %b %e %H:%M:%S %Z %Y".
func posixDate(t time.Time) string {
	day := t.Day()
	// POSIX %e pads single-digit days with a leading space.
	dayStr := fmt.Sprintf("%2d", day)
	return fmt.Sprintf("%s %s %s %s UTC %d",
		t.Format("Mon"),
		t.Format("Jan"),
		dayStr,
		t.Format("15:04:05"),
		t.Year())
}
