#!/usr/bin/env bash
# Single-shot wrapper around the feed-enrichment agent.
#
# Responsibilities:
#   1. Refuse non-primary feeds (retention derivatives, merges, internal URLs).
#   2. Snapshot the current prompt + schema into the run directory so each
#      run is a frozen point-in-time artifact for diffing across iterations.
#   3. Invoke ai-agent ONCE with --verbose. No wrapper-level retries —
#      every failure is a prompt/schema iteration signal, not a
#      budget-burning retry. The ai-agent runtime already re-prompts
#      internally on schema violations; that is the only retry layer we
#      accept. We trust ai-agent's exit code (0 = stdout JSON is valid
#      and schema-conformant; non-0 = model gave up).
#   4. Validate with agents/validate-output.py (extra checks beyond schema:
#      denylist, IP leakage, content presence).
#   5. Report SUCCESS or FAILED. Artifacts are always kept under
#      .local/agents/feed-enrichment/<feed>/<UTC>/ for inspection.
#
# Usage:
#   agents/run-enrichment.sh <feed_name>
#
# Reads the feed's YAML from configs/firehol/sources/*/<feed_name>.yaml.

set -euo pipefail

FEED="${1:?usage: run-enrichment.sh <feed_name>}"
# Single attempt. Failures are signals that the prompt or schema needs work.
# If you must rerun, invoke the script again after iterating the prompt.
# TIMEOUT_SEC: wall-clock budget for one full agent run. Pilot phase with
# --verbose + thorough multi-agent research can take 30-50 min for dead/
# obscure feeds that require many search rounds; 3600s (60 min) gives
# headroom while still hard-capping runaway recursion.
TIMEOUT_SEC="${TIMEOUT_SEC:-3600}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Enrichment runs only on feeds with a real upstream maintainer/publisher.
# Refuse any feed that we generate ourselves:
#   - secondary_retention (no YAML; built from the primary's history: field)
#   - secondary_merge    (YAML lives under configs/firehol/merges/)
# Both classes are auto-composed elsewhere (D5 in SOW-0014); calling the
# enrichment agent on them wastes compute and pollutes git history.
#
# Resolve the feed via agents/locate-feed.py — it parses YAMLs and matches
# the actual feed names declared under `sources:`, including sub-feeds in
# multi-source files (e.g., critical_provider_ranges.yaml declares 17
# distinct sub-feeds, none named "critical_provider_ranges").
LOCATE=$(agents/locate-feed.py "$FEED" 2>/dev/null)
if [[ -z "$LOCATE" ]]; then
    if [[ -f "configs/firehol/merges/${FEED}.yaml" ]]; then
        echo "REFUSED: '${FEED}' is a merge (configs/firehol/merges/${FEED}.yaml)."
        echo "         Merges are FireHOL-maintained; static enrichment is generated by"
        echo "         tools/build-firehol-static-enrichment.py."
        exit 4
    fi
    echo "REFUSED: no source for '${FEED}' in configs/firehol/sources/ YAMLs."
    echo "         If '${FEED}' is a retention derivative (e.g. ${FEED%_*}_1d/_7d/_30d), it is"
    echo "         generated locally from its primary's history: field — not researched."
    echo "         Run enrichment on the primary feed instead."
    exit 4
fi
# locate-feed.py returns: yaml_path\turl\tmaintainer\tcategory
# Missing fields are emitted as '-' so adjacent tabs don't collapse in
# `read`; we restore them to empty strings here.
YAML_PATH=$(echo -n "$LOCATE" | cut -f1)
FEED_URL=$(echo -n "$LOCATE" | cut -f2);   [[ "$FEED_URL"   == "-" ]] && FEED_URL=""
MAINTAINER=$(echo -n "$LOCATE" | cut -f3); [[ "$MAINTAINER" == "-" ]] && MAINTAINER=""
CATEGORY=$(echo -n "$LOCATE" | cut -f4);   [[ "$CATEGORY"   == "-" ]] && CATEGORY=""

# FireHOL-maintained feeds (the catalog's own merges, static reference lists, and
# internal-derived baselines) are NEVER researched by the agent. Enriching our
# own feeds would violate the no-firehol-self-reference rule and produce
# hall-of-mirrors output. Their enrichment is generated deterministically by
# tools/build-firehol-static-enrichment.py. See SOW-0014 (AI-in-the-loop) and
# SOW-0016 (review-firehol-merges) for the policy and long-term direction.
if [[ "$MAINTAINER" == "FireHOL" ]]; then
    echo "REFUSED: '${FEED}' is FireHOL-maintained — agent enrichment is forbidden by the"
    echo "         no-firehol-self-reference rule. Run tools/build-firehol-static-enrichment.py"
    echo "         to (re)generate its static enrichment instead."
    exit 4
fi

# Any internal:// URL means the feed is locally-generated and must not be enriched.
if [[ "$FEED_URL" == internal://* ]]; then
    echo "REFUSED: '${FEED}' has internal upstream URL '${FEED_URL}'."
    echo "         This indicates a locally-generated derivative; enrichment is not applicable."
    exit 4
fi

# Engine's last-update timestamp for this feed. Pass to the agent so it
# can calibrate research depth without re-discovering it from sources.
# Fail soft: if the running daemon is unreachable, send null.
LAST_OBSERVED_UPDATE=$(curl -s --max-time 5 "http://localhost:18888/api/v1/sets/${FEED}" 2>/dev/null \
    | python3 -c "import sys,json; d=json.load(sys.stdin); ts=d.get('source_date',0); print(__import__('datetime').datetime.utcfromtimestamp(ts).isoformat()+'Z' if ts else 'null')" 2>/dev/null || echo "null")

RUN_TS=$(date -u +%Y%m%dT%H%M%SZ)
RUN_DIR=".local/agents/feed-enrichment/${FEED}/${RUN_TS}"
mkdir -p "$RUN_DIR"

# Snapshot prompt + schema for this run
cp agents/feed-enrichment.ai      "$RUN_DIR/prompt.ai"
cp agents/schemas/feed-enrichment.schema.json "$RUN_DIR/schema.json"

# Build the input JSON.
#
# For multi-source YAML files (a single .yaml declaring several feeds under
# `sources:`), pass only the relevant sub-feed's block — not the whole file.
# Otherwise the agent sees N feeds in feed_yaml and has to guess which one
# is the target.
python3 - "$RUN_DIR" "$FEED" "$YAML_PATH" "$CATEGORY" "$LAST_OBSERVED_UPDATE" <<'PY'
import sys, json, pathlib, yaml as yamllib
run_dir, feed_name, yaml_path, category, last_update_raw = sys.argv[1:6]
full_text = pathlib.Path(yaml_path).read_text()
try:
    data = yamllib.safe_load(full_text)
    srcs = (data or {}).get("sources") or {}
    if feed_name in srcs:
        # Re-serialize just this sub-feed's block, preserving the canonical
        # `sources:\n  <feed_name>:\n    ...` shape the agent expects.
        sub = {"sources": {feed_name: srcs[feed_name]}}
        feed_yaml = yamllib.safe_dump(sub, sort_keys=False, default_flow_style=False)
    else:
        feed_yaml = full_text
except Exception:
    feed_yaml = full_text
obj = {"feed_name": feed_name, "feed_yaml": feed_yaml, "category": category}
last_update = None if last_update_raw == "null" else last_update_raw
obj["last_observed_update"] = last_update
pathlib.Path(f"{run_dir}/input.json").write_text(json.dumps(obj))
PY

# SINGLE attempt. No wrapper-level retries.
#
# Discipline: every failure is a prompt-iteration signal, not a budget-burning
# retry. SERP, scraping APIs, and external sub-agent costs make blind retries
# wasteful. The ai-agent runtime already retries internally on schema-invalid
# output (re-prompts the model with the validation error); that's the only
# retry layer we accept. If the wrapper finds violations after the runtime
# is done, the prompt is weak — fix it, then run again.
#
# Exit-code contract with ai-agent:
#   0       = model responded and schema-valid output is on stdout
#   non-0   = model failed to respond after its internal retries gave up
# We trust that contract. No stderr parsing.

echo "[run-enrichment] feed=${FEED} ts=${RUN_TS}"
USER_INPUT=$(cat "$RUN_DIR/input.json")
OUT="$RUN_DIR/output.json"
LOG="$RUN_DIR/agent.log"
REPORT="$RUN_DIR/validation-report.json"

# --verbose: full execution log (timings, tokens, tool calls) goes to LOG.
# --cache off: pilot phase needs fresh runs (avoids stale cached failures
# silently replaying). When the prompt is stable for production cadence,
# remove the flag so quarterly re-runs can reuse unchanged results.
set +e
timeout "$TIMEOUT_SEC" ai-agent --verbose --cache off agents/feed-enrichment.ai "$USER_INPUT" > "$OUT" 2> "$LOG"
agent_exit=$?
set -e

if [[ $agent_exit -ne 0 ]]; then
    echo "[run-enrichment] FAILED — ai-agent exit=${agent_exit}. Log: $LOG"
    exit 3
fi

python3 agents/validate-output.py "$OUT" --report "$REPORT" > /dev/null 2>&1 || true

schema_valid=$(jq -r '.schema_valid' "$REPORT")
deny_count=$(jq -r '.summary.denylist_violations_count' "$REPORT")
ip_count=$(jq -r '.summary.ip_address_findings_count' "$REPORT")
evidence_count=$(jq -r '.summary.evidence_count // 0' "$REPORT")
roles_count=$(jq -r '.summary.roles_count // 0' "$REPORT")

# Content presence: a real research run gathered some evidence and
# identified at least one role. Empty/rate-limited runs (the agent gave
# up before reaching sources) fail this check.
has_real_content=0
if [[ "$evidence_count" -ge 3 ]] && [[ "$roles_count" -ge 1 ]]; then
    has_real_content=1
fi

echo "[run-enrichment] result: schema_valid=${schema_valid} denylist=${deny_count} ip_findings=${ip_count} evidence=${evidence_count} roles=${roles_count} content_ok=${has_real_content}"

if [[ "$schema_valid" == "true" \
   && "$deny_count" == "0" \
   && "$ip_count" == "0" \
   && "$has_real_content" == "1" ]]; then
    echo "[run-enrichment] SUCCESS. Output: $OUT"
    exit 0
fi

echo "[run-enrichment] FAILED — validation reported issues. Artifacts kept in $RUN_DIR."
echo "                 Iterate the prompt or schema and run again — no automatic retry."
exit 1
